name: Bedwars1058-Voidless
version: '${project.version}'
main: me.zuyte.voidless.Main
softdepend: [ BedWars1058 ]
api-version: "1.13"
authors: [ Zuyte ]
description: Automatically builds bed defence for voidless gamemode
